### ISSUE TITLE
Como Usuário gostaria de informar um Status do RU

### ISSUE THREAD

**Issue by Marinofull** [Marinofull/micro-twit-ru#3]
**Status**
- Fila:
  - Fila grande;
  - Fila pequena;
- Fichas:
  - Fichas acabaram;
- Cardápio:
  - Comida Muito Boa;
  - Comida razoável;
  - "Só tem Soja viu bem?";
  - "Peixe";
  - "Fígado";
  - "Charutinho de soja";
  - Contém `anomalias`.

**Comment by Marinofull** [comment]
@caiolima @niltonvasques
Pensei nesses statuses se acumularem num da mesma categoria.
Exemplo: 
**20 pessoas postam**
- 12 Fila grande;
- 2 "Peixe";
- 8 Contém `anomalias`.

Ao invés de aparecerem 20 postagens na timeline, surgem apenas 3, com a quantidade de postagens/replicações ao lado. Caso mais uma pessoa replique o poste `Peixe`, então este incrementará o contador para **3**.

**Comment by caiolima** [comment]
To aqui
